/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_

const char *draw_frag =
 "#version 130\n"
 "#define iResolution gl_TexCoord[0]\n"
 "#define iTime gl_TexCoord[0].z\n"
 "#define pi acos(-1.)\n"
 "vec2 s(vec2 v,float m)"
 "{"
   "float y=cos(m),z=sin(m);"
   "return vec2(v.x*y-v.y*z,v.x*z+v.y*y);"
 "}"
 "float n(vec3 v,vec3 y)"
 "{"
   "return v=abs(v)-y,max(max(v.x,v.y),v.z);"
 "}"
 "float f(vec3 v,vec2 y)"
 "{"
   "vec2 m=vec2(length(v.xz)-y.x,v.y);"
   "return length(m)-y.y;"
 "}"
 "vec2 f(const float v)"
 "{"
   "return fract(sin(vec2(v,v+1.))*vec2(43758.5));"
 "}"
 "int v;"
 "float n(vec3 v)"
 "{"
   "float i=1e+09,y=length(v.yx)-1.5;"
   "i=-y;"
   "{"
     "vec3 m=v;"
     "m.z=mod(m.z,.4)-.2;"
     "i=min(i,f(m.xzy,vec2(1.51,.02)));"
   "}"
   "float m=v.y+1.;"
   "i=min(i,m);"
   "{"
     "vec3 r=v;"
     "r.y+=.998;"
     "r.xz=s(r.xz,-pi*.25);"
     "r.xz=mod(r.xz,.1)-.05;"
     "i=max(i,.005-length(r.yx));"
     "i=max(i,.005-length(r.yz));"
   "}"
   "return i;"
 "}"
 "float s(vec3 v)"
 "{"
   "float i=4.93;"
   "i=6.;"
   "float m=1e+09;"
   "{"
     "vec3 r=v;"
     "r.x=abs(r.x);"
     "r.xy+=vec2(-1.1,1);"
     "m=min(m,max(length(r.yx)-.05,abs(mod(r.z-1.,2.)-1.)-.01));"
     "m=max(m,1.-abs(v.z));"
   "}"
   "{"
     "vec3 r=v;"
     "r.xy=s(r.xy,-pi*.25);"
     "m=min(m,max(abs(r.z)-.1,abs(mod(r.y-.1,.2)-.1)-.01));"
   "}"
   "return m;"
 "}"
 "float m(vec3 m)"
 "{"
   "float y=n(m),i=s(m);"
   "v=i<y?1:0;"
   "return min(i,y);"
 "}"
 "vec2 i;"
 "vec3 x(vec3 v)"
 "{"
   "float m=2.*pi*i.x,y=acos(1.-2.*i.y),r=sin(y)*cos(m),z=sin(y)*sin(m),x=cos(y);"
   "vec3 f=normalize(vec3(r,z,x));"
   "return dot(f,v)<0.?-f:f;"
 "}"
 "vec3 m(vec3 r,vec3 y)"
 "{"
   "vec3 f=vec3(1);"
   "for(int z=0;z<4;++z)"
     "{"
       "float e=0.,a;"
       "for(int g=0;g<100;++g)"
         "{"
           "a=m(r+y*e);"
           "e+=a;"
           "if(abs(a)<.001)"
             "break;"
         "}"
       "vec3 n=r+y*e;"
       "if(abs(a)<.001)"
         "{"
           "if(v==1)"
             "{"
               "if(abs(n.z)<.2)"
                 "return vec3(1,.15,.15)*f;"
               "else"
                 " return vec3(5,2,.5)*f;"
             "}"
           "vec2 g=vec2(.001,0);"
           "a=m(n);"
           "vec3 l=normalize(vec3(m(n+g.xyy)-a,m(n+g.yxy)-a,m(n+g.yyx)-a));"
           "float s=.85;"
           "if(n.y<=-.999)"
             "{"
               "if(i.x<.95)"
                 "f*=.125,s=.01;"
             "}"
           "r=n+l*.001;"
           "vec3 c=reflect(y,l),d=x(l);"
           "y=normalize(mix(c,d,s));"
           "f*=mix(1.,dot(y,l),s);"
         "}"
     "}"
   "return vec3(0);"
 "}"
 "vec2 f()"
 "{"
   "vec2 v=i;"
   "if(v.y>v.x)"
     "v=1.-v;"
   "v.y*=pi*2./v.x;"
   "return v.x*vec2(cos(v.y),sin(v.y));"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/iResolution.xy-.5;"
   "float r=iTime;"
   "i=f(r);"
   "v+=(i-.5)/iResolution.xy;"
   "v.x*=iResolution.x/iResolution.y;"
   "{"
     "float y=exp2(clamp(floor(length(v)*9.),2.,9.));"
     "r+=mod(floor(gl_FragCoord.x/y),1.34672);"
     "r+=mod(floor(gl_FragCoord.y/y),1.72357);"
     "i=f(r);"
   "}"
   "vec3 y=vec3(0,0,-8.),z=normalize(vec3(v,1));"
   "float x=.005;"
   "vec2 n=f();"
   "y.xy+=n*x;"
   "z.xy-=n*x*z.z/8.;"
   "y.y-=.25;"
   "z.yz=s(z.yz,.06);"
   "vec4 g=vec4(m(y,z),1);"
   "gl_FragColor=g.x>=0.?g:vec4(0);"
 "}";

#endif // FRAG_DRAW_H_
